config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  resource  :likes, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: 'search'

  root to: "homes#top"
  get 'home/about' => "homes#about", as:'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_one_attached :profile_image

    has_many :books, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

    validates :name, length: { in: 2..20 }, uniqueness: true
    validates :introduction, length: { maximum: 50 }

    def get_profile_image(width, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/default-image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [width, height]).processed
    end

  def self.search_for(word, method)
    if method == 'perfect_match'
      User.where(name: word)
    elsif method == 'forward_match'
      User.where('name LIKE ?', word+'%')
    elsif method == 'backward_match'
      User.where('name LIKE ?', '%'+word)
    elsif method
      User.where('name LIKE ?', '%'+word+'%')
    end
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
def after_sign_up_path_for(resource)
    flash[:notice] = 'Welcome! You have signed up successfully.'
    user_path(current_user)
end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @book = Book.new

  end

  def show
    @user = User.find(params[:id])
     @book = Book.new
    @books = @user.books


  end

  def edit
    is_matching_user
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_user
    user = User.find(params[:id])
    unless user.id == current_user.id
    redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>

<table class="table">
 <tbody>

  <tr></tr>
     <th>name</th><th><%= user.name %></th>
  </tr>
  <tr>
     <th>introduction</th><th><%= user.introduction %></th>
  </tr>
 </tbody>
</table>

<div class="row">

<%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>User info</h2>

<% if @user.errors.any? %>
<h3><strong><%= @user.errors.count %>errors prohibited this obj from being saved:</strong></h3>
<ul><% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
<% end %>
</ul>
<% end %>

<%= form_with model: @user do |f| %>
<div class="form-group"><p>Name</p>
<%= f.text_field :name %>
</div>
<div class="form-group">
<p>Image</p>
<%= f.file_field :profile_image, accept: "image/*" %>
</div>
<div class="form-group">
<p>Introduction</p>
<%= f.text_area :introduction, class:"form-control" %>
</div>
<br>
<div class="form-group">
<%= f.submit "Update User", class: "btn btn-secondary" %>
</div>
<% end %>

   </div>
  </div>
 </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <div class="col-md-3">
<%= render 'users/info', user: current_user %>
<h2 class="mt-3">New book</h2>
<%= render 'books/post', book: @book %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Users</h2>

 <table class="table">
   <thead>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
   </thead>
   <tbody>
     <% @users.each do |user| %>
     <tr>
       <td><%= image_tag user.get_profile_image(80,80) %></td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
     <% end %>
   </tbody>

 </table>
 </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

<div class="col-md-3">
<%= render 'users/info', user: @user %>
<%= render 'books/post', book: @book %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class ="table table-hover table-inverse">
    <thead>
        <th></th>
        <th>Title</th>
        <th>Opnion</th>
        <th colspan="3"></th>
    </thead>
    <tbody>
     <% @books.each do |book| %>
    <tr>
     <td>
       <%= link_to user_path(@user.id) do %>
       <%= image_tag book.user.get_profile_image(80,80) %>
     </td>
     <% end %>
     <td>
       <%= link_to book_path(book.id) do %>
       <%= book.title %>
       <% end %>
     </td>
     <td>
       <%= book.body %>
     </td>
     </tr>
     <% end %>
    </tbody>
</table>
</div>

 </div>
</div>