config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  resource  :likes, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: 'search'

  root to: "homes#top"
  get 'home/about' => "homes#about", as:'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def self.search_for(word, method)
    if method == 'perfect_match'
      Book.where(title: word)
    elsif method == 'forward_match'
      Book.where('title LIKE ?', word+'%')
    elsif method == 'backward_match'
      Book.where('title LIKE ?', '%'+word)
    else
      Book.where('title LIKE ?', '%'+word+'%')
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_book, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
    else
      @books = Book.all
    render 'index'
    end
  end

  def index
  @books = Book.all
  @book = Book.new
  @book_comment = BookComment.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    is_matching_book
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def is_matching_book
    book = Book.find(params[:id])
    user = book.user
    unless user.id  == current_user.id
      redirect_to books_path
    end
  end



end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_post.html.erb
<%= form_with model: book do |f| %>
<p>Title</p><%= f.text_field :title, class:"form-control" %>
<p>Opinion</p><%= f.text_area :body, class:"form-control" %><br>


<% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label "星評価" %>
      <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[rate]',
        };
        raty(elem, opt);
      });
    </script>


  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>

  <%= f.submit "Create Book", class: "btn btn-success" %>

<% end %>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#rate_<%= book.id %>');
  if (elem == null) return;

  elem.innerHTML = "";
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.rate %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h1>Editing Book</h1>

<% if @book.errors.any? %>
<h3><strong><%= @book.errors.count %>errors prohibited this obj from being saved:</strong></h3>
<ul><% @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
<% end %>
</ul>
<% end %>

<%= render 'post', book: @book %>

<%= link_to "Show", book_path(@book) %>|
<%= link_to "Back", books_path %>

  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
<h3><strong><%= @book.errors.count %>errors prohibited this obj from being saved:</strong></h3>
<ul><% @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
<% end %>
</ul>
<% end %>

 <div class="row">

<div class="col-md-3">

<%= render 'users/info', user: current_user %>
<h2 class="mt-3">New book</h2>
<%= render 'post', book: @book %>
</div>

<div class="col-md-8 offset-md-1">

<h2>Books</h2>

<table class ="table">
    <thead>
        <th></th>
        <th>Title</th>
        <th>Opnion</th>
        <th></th>
        <th colspan="3"></th>
    </thead>
    <tbody>
     <% @books.each do |book| %>
    <tr>
     <td>
       <%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(80,80) %>
       <% end %>
     </td>
     <td>
          <%= link_to book_path(book.id) do %>
       <%= book.title %>
          <% end %>

     </td>


     <td>
       <%= book.body %>

     </td>
     <td id="like_btn_<%= book.id %>">
         <%= render  partial: "likes/like", locals: {book: book} %>

     </td>
     <td>
         コメント数:<%= book.book_comments.count %>
     </td>
     <td><%= render "static_rate", book: book %></td>
     </tr>
     <!--<tr>-->
     <!--    <td>-->
     <%#= form_with model: [book, @book_comment] do |f| %>
       <%#= f.text_area :comment, placeholder: "コメントをここに", class: "w-100" %>
       <%#= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
     <%# end %>
     <!--    </td>-->
     <!--</tr>-->
     <!--<tr>-->
      <%# book.book_comments.each do |book_comment| %>
       <!--<tr>-->
       <!-- <td>-->
            <%#= image_tag book_comment.user.get_profile_image(100,100) %><!--<br>
            <%#= book_comment.user.name %>
        <%#= book_comment.comment %></td>
            <%# if book_comment.user == current_user %>
        <td><%#= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %></td>
          <%# end %>
          <%# end %>
     <!--</tr>-->

    </tbody>
    <% end %>

</table>
</div>

 </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<% if @book.errors.any? %>
<%= @book.errors.count %><strong>errors prohibited this obj from being saved:</strong>
<ul><% @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
<% end %>
</ul>
<% end %>

<%= form_with model: @book do |f| %>
<p>Title</p><%= f.text_field :title %>
<p>Opinion</p><%= f.text_area :body %><br>
<%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <div class="col-md-3">
<%= render 'users/info', user: @user %>
<%= render 'post', book: Book.new %>

</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
 <tbody>
 <tr>
   <td>
    <%= image_tag @book.user.get_profile_image(100,100) %><br>
    <%= link_to user_path(@user.id) do %>
    <%= @book.user.name %>
    <% end %>
   </td>

 <td>
       <%= link_to book_path(@book.id) do %>
       <%= @book.title %>
    <% end %>
     </td>
  <td>
    <%= @book.body %>
  </td>
   <td id="like_btn_<%= @book.id %>">
         <%= render  partial: "likes/like", locals: {book: @book} %>
     </td>

      <td><%= render "static_rate", book: @book %></td>

     <td class="counts_comment">
      <%= render "book_comments/count", book: @book %>
     </td>


     <div>
        <% if @user == current_user %>
           <td>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
           </td>
           <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %>
         <% end %>
           </td>
     </div>
    </tr>
  </tbody>
</table>

<div class="comments_index">
 <%= render "book_comments/comment_index", book: @book %>
</div>

<div class="comments_form">
 <%= render "book_comments/comment_form", book: @book, book_comment: @book_comment %>
</div>

    </div>
  </div>
</div>