config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  resource  :likes, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: 'search'

  root to: "homes#top"
  get 'home/about' => "homes#about", as:'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  def search
    @word = params[:word]
    @model = params[:model]
    # @method = params[:method]
     if @model == "User"
       @records = User.search_for(@word, @method)
     else
       @records = Book.search_for(@word, @method)
     end
  end
  def index
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%if user_signed_in? %>
    <%= form_with url: search_path, method: :get, local: true do |f| %>

    <%= f.text_field :word %>
    <%= f.select :model, options_for_select([['User'], ['Book']]) %>
    <%= f.select :method, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索" %>
    <% end %>
<% end %>

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>

app/views/searches/search.html.erb
<% if @model == 'User' %>
<h3>Users search for "<%= @word %>"</h3>

 <table class="table">
   <thead>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
   </thead>
   <tbody>
     <% @records.each do |user| %>
     <tr>
       <td><%= image_tag user.get_profile_image(80,80) %></td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
     <% end %>
   </tbody>
 </table>
<% elsif @model == 'Book' %>
  <h3>Books search for "<%= @word %>"</h3>
  <table class ="table">
    <thead>
        <th></th>
        <th>Title</th>
        <th>Opnion</th>
        <th></th>
        <th colspan="3"></th>
    </thead>
    <tbody>
     <% @records.each do |book| %>
    <tr>
     <td>
       <%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(80,80) %>
       <% end %>
     </td>
     <td>
          <%= link_to book_path(book.id) do %>
       <%= book.title %>
          <% end %>

     </td>


     <td>
       <%= book.body %>

     </td>
     <td>
      <% if book.liked_by?(current_user) %>
        <%= link_to book_likes_path(book), method: :delete do %>
        <i class="fas fa-heart"></i>
        <%= book.likes.count %>
      <% end %>
      <% else %>
        <%= link_to book_likes_path(book), method: :post do %>
        <i class="far fa-heart"></i>
        <%= book.likes.count %>
        <% end %>
      <% end %>
     </td>
     <td>
         コメント数:<%= book.book_comments.count %>
     </td>
     </tr>
     <!--<tr>-->
     <!--    <td>-->
     <%#= form_with model: [book, @book_comment] do |f| %>
       <%#= f.text_area :comment, placeholder: "コメントをここに", class: "w-100" %>
       <%#= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
     <%# end %>
     <!--    </td>-->
     <!--</tr>-->
     <!--<tr>-->
      <%# book.book_comments.each do |book_comment| %>
       <!--<tr>-->
       <!-- <td>-->
            <%#= image_tag book_comment.user.get_profile_image(100,100) %><!--<br>
            <%#= book_comment.user.name %>
        <%#= book_comment.comment %></td>
            <%# if book_comment.user == current_user %>
        <td><%#= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %></td>
          <%# end %>
          <%# end %>
     <!--</tr>-->

    </tbody>
    <% end %>

</table>
<% end %>