config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  resource  :likes, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: 'search'

  root to: "homes#top"
  get 'home/about' => "homes#about", as:'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def self.search_for(word, method)
    if method == 'perfect_match'
      Book.where(title: word)
    elsif method == 'forward_match'
      Book.where('title LIKE ?', word+'%')
    elsif method == 'backward_match'
      Book.where('title LIKE ?', '%'+word)
    else
      Book.where('title LIKE ?', '%'+word+'%')
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_one_attached :profile_image

    has_many :books, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

    validates :name, length: { in: 2..20 }, uniqueness: true
    validates :introduction, length: { maximum: 50 }

    def get_profile_image(width, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/default-image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [width, height]).processed
    end

  def self.search_for(word, method)
    if method == 'perfect_match'
      User.where(name: word)
    elsif method == 'forward_match'
      User.where('name LIKE ?', word+'%')
    elsif method == 'backward_match'
      User.where('name LIKE ?', '%'+word)
    elsif method
      User.where('name LIKE ?', '%'+word+'%')
    end
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_up_path_for(resource)
    flash[:notice] = 'Welcome! You have signed up successfully.'
    user_path(current_user)
en
def after_sign_in_path_for(resource)
    flash[:notice] = 'Signed in successfully.'
    user_path(current_user)
end
  def after_sign_out_path_for(resource)
      flash[:notice] = 'Signed out successfully.'
  '/'
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_book, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
    else
      @books = Book.all
    render 'index'
    end
  end

  def index
  @books = Book.all
  @book = Book.new
  @book_comment = BookComment.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    is_matching_book
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def is_matching_book
    book = Book.find(params[:id])
    user = book.user
    unless user.id  == current_user.id
      redirect_to books_path
    end
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    like = current_user.likes.new(book_id: @book.id)
    like.save
    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    like = current_user.likes.find_by(book_id: @book.id)
    like.destroy
    # redirect_to request.referer
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  def search
    @word = params[:word]
    @model = params[:model]
    # @method = params[:method]
     if @model == "User"
       @records = User.search_for(@word, @method)
     else
       @records = Book.search_for(@word, @method)
     end
  end
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @book = Book.new

  end

  def show
    @user = User.find(params[:id])
     @book = Book.new
    @books = @user.books


  end

  def edit
    is_matching_user
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_user
    user = User.find(params[:id])
    unless user.id == current_user.id
    redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                     aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i> <span>Home</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class: 'nav-link text-light' do %>
       <i class="fas fa-users"> </i> <span>Users</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class: 'nav-link text-light' do %>
        <i class="fas fa-book-open"> </i> <span>Books</span>
        <% end %>
      </li>
       <li class="nav-item">
         <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
         <i class="fas fa-sign-out-alt"></i> <span>Log out</span>
         <% end %>
      </li>
 <% else %>
      <li class="nav-item">
      <%= link_to root_path, class: 'nav-link text-light' do %>
      <i class="fas fa-home"></i> <span>Home</span>
        <% end %>
      </li>
      <li class="nav-item">
      <%= link_to about_path, class: 'nav-link text-light' do %>
       <i class="fas fa-link"></i> <span>About</span>
       <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i> <span>Sign up</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i> <span>Log in</span>
        <% end %>
      </li>
      <% end %>
        </ul>


      　</div>
       </div>
     </nav>
 </header>
<p><%= flash[:notice] %></p>
<%= render 'searches/form' %>

    <%= yield %>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
    <p>CopyRight Infratop.inc</p>
    </div>
   </div>
   </div>
  </footer>
</html>